### ISSUE TITLE
'Timeout' in Petitboot System Configuration can not be saved

### ISSUE THREAD

**Issue by bogatseng** [open-power/petitboot#1]
Hi,

We change "Timeout" for auto-boot setting in Petitboot System Configuration and choose "OK", but the setting can NOT be saved. Please see the attached file: TimeoutNotSave.png 

![timeoutnotsave](https://cloud.githubusercontent.com/assets/13481450/9489020/80d718ce-4c10-11e5-87f4-a5969f2b3f26.png)

Cheers,
Boga

**Comment by sammj** [comment]
This is probably because your build is missing the nvram utility from powerpc-utils. This was fixed in https://github.com/open-power/op-build/pull/235
