### ISSUE TITLE
Petitboot: v1.15: No video output after kexec

### ISSUE THREAD

**Issue by carlosgonz0** [open-power/petitboot#109]
I have a  very weird issue on Petitboot 1.15 that the Operating system can not video output after kexec, however after unlock luks by serial console the video output come work, however older Petitboot  version worked without to use serial console to unlock luks. 
Computer Blackbird Power9, Linux 6.8.8, Mesa 23.2
Thanks

**Comment by jk-ozlabs** [comment]
The petitboot process itself doesn't control any of the video output; you'll want to check out what the kernel is doing with regards to the video driver init (and behaviour over kexec).

Do blackbird have a mechanism to support the kernel used there?

**Comment by jk-ozlabs** [comment]
> Ok i will try to get traces about ast driver on host. Ok looks like the issue will be at Linux in Skiroot i guess.

Yep, the traces from the host ast driver would be handy there. I can take a look at those, but it has been a while since I have dealt with the ast video driver!

> I not sure what you mean to say?

The folks that provided your petitboot update - do they have a mechanism to support that update?

**Comment by carlosgonz0** [comment]
> The folks that provided your petitboot update - do they have a mechanism to support that update?

They shipped  Petitiboot 1.15 as you can see on changelog:
PNOR

    Update hostboot to latest upstream version
    Update skiboot to latest upstream version
    Update petitboot to latest upstream version
    Update hcode to latest upstream version
    Update skiroot to Linux 6.6.y stable branch
    Enable Infiniband drivers in skiroot
    Fix sporadic crash on paired-core machines (higher than 8 core) under specific workloads
    Compress hostboot runtime to free up additional space in the BOOTKERNFW partition
    Enable firmware component signature checks during IPL by default. Note that this uses the well-known (insecure) public transitional key in the official firmware builds, but makes the transition to a machine owner's key easier should the user wish to enable a secure boot chain using their own signing keys.


https://gitlab.raptorengineering.com/openpower-firmware/machine-blackbird/op-build/-/commits/02-29-2024/

I really interested what is going on... i will share the ast host traces here soon.


Thanks of advance

**Comment by carlosgonz0** [comment]
carlosgonz@blackbird:~$ dmesg | grep ast
dmesg: read kernel buffer failed: Operation not permitted
carlosgonz@blackbird:~$ sudo dmesg | grep ast
[sudo] password for carlosgonz: 
[    0.678486] ast 0005:02:00.0: enabling device (0140 -> 0142)
[    0.678498] ast 0005:02:00.0: Using device-tree for configuration
[    0.678501] ast 0005:02:00.0: AST 2500 detected
[    0.678580] ast 0005:02:00.0: [drm] Using Sil164 TMDS transmitter
[    0.678585] ast 0005:02:00.0: [drm] dram MCLK=800 Mhz type=7 bus_width=16
[    0.679179] [drm] Initialized ast 0.1.0 20120228 for 0005:02:00.0 on minor 0
[    0.682389] ast 0005:02:00.0: [drm] fb0: astdrmfb frame buffer device
[   45.775068] Bluetooth: BNEP filters: protocol multicast
carlosgonz@blackbird:~$ sudo dmesg | grep failed
[    0.138314] pci 0000:00:00.0: bridge window [io  size 0x1000]: failed to assign
[    0.138408] pci 0000:01:00.0: BAR 4 [io  size 0x0100]: failed to assign
[    0.138553] pci 0002:00:00.0: bridge window [io  size 0x1000]: failed to assign
[    0.138579] pci 0002:01:00.0: BAR 4 [io  size 0x0020]: failed to assign
[    0.138588] pci 0002:01:00.0: BAR 0 [io  size 0x0008]: failed to assign
[    0.138597] pci 0002:01:00.0: BAR 2 [io  size 0x0008]: failed to assign
[    0.138606] pci 0002:01:00.0: BAR 1 [io  size 0x0004]: failed to assign
[    0.138615] pci 0002:01:00.0: BAR 3 [io  size 0x0004]: failed to assign
[    0.139044] pci 0005:00:00.0: bridge window [io  size 0x1000]: failed to assign
[    0.139059] pci 0005:01:00.0: bridge window [io  size 0x1000]: failed to assign
[    0.139091] pci 0005:02:00.0: BAR 2 [io  size 0x0080]: failed to assign
carlosgonz@blackbird:~$

**Comment by carlosgonz0** [comment]
OK i fixed the issue by adding...

ast to: /etc/initramfs-tools/modules then update-initramfs -u -k all
console=tty0 to: /etc/default/grub(GRUB_CMDLINE_LINUX="console=tty0") then update-grub

Full thanks to @jk-ozlabs for the support.

**Comment by jk-ozlabs** [comment]
Oh, great to hear that it's sorted. Just for my own understanding & public record: the fix included:

* incorporating the `ast` driver into the host system's initramfs
* configuring for a kernel console on tty0 (ie, the video console device)

Is that correct? (mainly: the initramfs you're referring to was the installed OS' one, right?)

**Comment by carlosgonz0** [comment]
> Is that correct? 

Yes it correct.

> (mainly: the initramfs you're referring to was the installed OS' one, right?)

Yes on an installed OS and on my case i using: Gnu OS (trisquel aramo).
