### ISSUE TITLE
Support file:// URLs to help developers

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/petitboot#16]
Feature request to support file:/// URLs for "Retrieve config from URL" to help people in the lap/doing things they probably shouldn't.

**Comment by sammj** [comment]
Oddly enough I was just finishing up this exact patch - is there anything desired apart from accessing 'local' configuration files?

**Comment by sammj** [comment]
Added in https://github.com/open-power/petitboot/commit/ed8a3ad086e56fa40c72c531b3f563e35a7c0753
