### ISSUE TITLE
Keyboard didn't work under petitboot

### ISSUE THREAD

**Issue by sword-huang** [open-power/petitboot#17]
Platform: Firestone

Firmware Version:
PNOR: op-build tag V1.8
BMC: AMI's version 2.13.92578 of 03172016_Src_Release

Scenario
1. Console keyboard can’t work.
2. BMC KVM keyboard can’t work.
3. BMC SOL keyboard CAN work.
4. Plug again the USB keyboard. The keyboard will work.
5. Go to the OS.  The keyboard will work.
6. Petitboot shell only get two USB Devices. Can't get keyboard.

```
 / # lsusb
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003
```
1. Show some errors message in Skiboot.

```
[   28.428725] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   28.738770] ehci-pci: EHCI PCI platform driver
[   28.898450] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[   29.159950] ohci-pci: OHCI PCI platform driver
[   29.569686] xhci_hcd 0003:0d:00.0: xHCI Host Controller
[   29.737621] xhci_hcd 0003:0d:00.0: new USB bus registered, assigned bus number 1
[   29.827904] xhci_hcd 0003:0d:00.0: Using 64-bit DMA iommu bypass
[   30.013013] xhci_hcd 0003:0d:00.0: hcc params 0x0270f06d hci version 0x96 quirks 0x00000000
[   30.158136] hub 1-0:1.0: USB hub found
[   30.545330] hub 1-0:1.0: 4 ports detected
[   30.852700] xhci_hcd 0003:0d:00.0: xHCI Host Controller
[   31.044243] xhci_hcd 0003:0d:00.0: new USB bus registered, assigned bus number 2
**[   31.142863] usb usb1-port1: couldn't allocate usb_device**
**[   31.142877] usb usb1-port3: couldn't allocate usb_device**
[   31.587662] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[   32.018553] hub 2-0:1.0: USB hub found
[   32.067570] hub 2-0:1.0: 4 ports detected
```

How to reproduce
1. Use BMC KVM to operate Petitboot menu.
2. If keyboard can work, reboot system by KVM menu.
3. Go to step1, test again.

**Comment by sammj** [comment]
This is probably related to the xhci issues described here: https://github.com/open-power/op-build/issues/307

**Comment by shenki** [comment]
The xhci issues are related to the way we shutdown the device when exiting the petitboot kernel. Due to the bug, it stays asleep when the host kernel comes up and we lose usb. The output of lsusb shows "libusb error -99".

Given that, I don't think this is related. It's a separate (new) bug!

**Comment by sword-huang** [comment]
I don't think this is related to open-power/op-build#307.

If I don't enable BMC KVM, I can't reproduce this issue over 30 times reboot in petitboot shell or OS. When I enable BMC KVM, this issue is very easy reproduce.

if I reset USB hub by manual in petitboot shell, the keyboard will work.

**Comment by sammj** [comment]
The USB situation in https://github.com/open-power/op-build has improved considerably over the past few months, does this still persist on a Firestone platform?

**Comment by sword-huang** [comment]
Because I don't work on it now. I will close this issue now.
