### ISSUE TITLE
petitboot UI left and right arrows not functioning

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/petitboot#20]
Noticed while editing command line for kernel over IPMI on garrison. can not go to start of line and then go forward character at a time.

**Comment by sammj** [comment]
Yep, we already have a fix but it's not quite merged yet - there'll be a v1.2.2 soon.
http://patchwork.ozlabs.org/patch/650977/

**Comment by sammj** [comment]
Fixed by https://github.com/open-power/petitboot/commit/297d2f0cc9c0a233fadf42dacc08708ad3909f77
