### ISSUE TITLE
disks are not visible on barreleye machine in petitboot

### ISSUE THREAD

**Issue by kachini** [open-power/petitboot#22]
I'm trying to install OS to the Barreleye server but petitboot don't see any disks. During server initial startup i also don't see any disks discovered on megaraid controller. 
In fact  we have two ssd disks installed and disk LED is light. 

Wondering if this is something known?

thanks in advance,

**Comment by sammj** [comment]
Hi @kachini, a few questions to narrow down the problem;

- What method are you using to install an OS (DVD, netboot, etc)?
- Do you know what version of Petitboot is running on the machine?
- Please post or link /var/log/messages and the logs under /var/log/petitboot/ (If pb-sos is available on the system it will collect these for you)
