### ISSUE TITLE
Mention disk when logging boot entries

### ISSUE THREAD

**Issue by ruscur** [open-power/petitboot#28]
I have two disks, `sda` and `sdb`, with identical boot entries:

```
 *[Disk: sda2 / 0d20c4db-1f6a-43cd-8989-21099678066a]
    Ubuntu, with Linux 4.10.0-20-generic (recovery mode)
    Ubuntu, with Linux 4.10.0-20-generic
    Ubuntu
  [Disk: sdb2 / b011e264-4e00-41f3-a482-49d1e47fdaa5]
    Ubuntu, with Linux 4.10.0-20-generic (recovery mode)  
    Ubuntu, with Linux 4.10.0-20-generic
    Ubuntu
```

I don't know which one will autoboot.  I'm guessing `sda` because of the asterisk?

In the log, I see `Booting in 10 sec: Ubuntu`, which isn't particularly useful.  It'd be nice if it said `Booting in 10 sec: [sda2] Ubuntu` for example.

**Comment by sammj** [comment]
Good idea, fixed here: https://github.com/open-power/petitboot/commit/2713a008a6b7fb9e63d5b8004fc39dae22e1abf7
