### ISSUE TITLE
IPMI Override vs Boot Order interaction

### ISSUE THREAD

**Issue by sammj** [open-power/petitboot#33]
There has been some confusion about whether IPMI boot overrides should interact with the current boot order.
For example, if the boot order specifies a particular disk and a disk override is set, should Petitboot preference the disk in the boot order, or treat all disks equally?

At the moment I'm leaning towards no interaction: IPMI overrides as I understand them are meant to cover the case of "I have no idea how this system is configured, but I want it to boot _this_". Giving consideration to the current config in this case would seem unexpected to me.
I think this should just be a documented behaviour, but I encourage any alternate viewpoints :)

**Comment by cyrilbur-ibm** [comment]
On Thu, 2017-10-12 at 03:36 +0000, Sam Mendoza-Jonas wrote:
> There has been some confusion about whether IPMI boot overrides should interact with the current boot order.
> For example, if the boot order specifies a particular disk and a disk override is set, should Petitboot preference the disk in the boot order, or treat all disks equally?
> At the moment I'm leaning towards no interaction: IPMI overrides as I understand them are meant to cover the case of "I have no idea how this system is configured, but I want it to boot this". Giving consideration to the current config in this case would seem unexpected to me.

For what its worth, I agree with this view.
