### ISSUE TITLE
Hotkey abnormal in Plugins page.

### ISSUE THREAD

**Issue by johnhihi** [open-power/petitboot#34]
In plugins page, the hotkeys "N", "G", "C", "I" would leaves the plugin page to "Option editor", "Status log", "System configuration", "System information" respectively.
Looks like the hotkey in plugin page are inherit from main page. Is it normal?

Another observation, after entering plugin page, the bottom line shows "Enter=install, e=details, x=exit, h=helpanguage, g=log, h=help". Seems there is not refresh the bottom line.

petitboot version : v1.6.3

**Comment by sammj** [comment]
Good catch! This is because the plugins menu will use the same `pmenu_process_key` handler for keystrokes, but a number of those shortcuts obviously aren't relevant in that context.
Most likely we should add an interface to pmenus to set a custom `process_key` handler.

**Comment by johnhihi** [comment]
Hi @sammj 
Do you have a target date to fix it?

**Comment by sammj** [comment]
Ah thanks for the reminder - in fact I just merged the fix recently, here: https://github.com/open-power/petitboot/commit/2dfbd9811d1e14911a6476850aada94b88a0dbdd

**Comment by johnhihi** [comment]
I will try it. Thanks a lot.

**Comment by johnhihi** [comment]
Hi @sammj 

The hotkey bug is fixed. Thanks a lot.

But there is still an abnormal string showing in hotkey illustration line.
You can see the abnormal symptom picture as shown below.
Seems there is not a refresh of the bottom line.
Do I need to open another thread to track this issue?

![petitboot_1](https://user-images.githubusercontent.com/13672992/34813299-6a8bb18e-f6e4-11e7-996b-7a350265557d.JPG)
![petitboot_2](https://user-images.githubusercontent.com/13672992/34813309-712a377c-f6e4-11e7-96e8-4b99aa8aa82d.JPG)

**Comment by sammj** [comment]
I suspect that's because of a missing screen refresh - lets track it here as well and I'll work on a quick fix.

**Comment by sammj** [comment]
Yep just a stale update - patch posted here: http://patchwork.ozlabs.org/patch/859509/

**Comment by johnhihi** [comment]
This patch also works. Look forward to merge it to main stream. Thanks.

**Comment by sammj** [comment]
Merged in v1.7.0: https://github.com/open-power/petitboot/commit/11c43508e4360456298a6dcb0563614e9a118b41
