### ISSUE TITLE
Autoboot not firing and booting from "Any Disk"

### ISSUE THREAD

**Issue by seanbruno** [open-power/petitboot#49]
I have "Any Disk" setup and autoboot set to 10, I think.  The autoboot timer never fires and heads off into FreeBSD.

http://people.freebsd.org/sbruno/pb-sos.tar.gz

**Comment by sammj** [comment]
That link 404s :)
First thing to check would be that whatever configuration format you're using for FreeBSD sets a 'default' option though; Petitboot will use that to determine if a boot option is valid for autoboot.

**Comment by seanbruno** [comment]
Oh ... hmmm.  I guess I need to add a default option here:

# cat /mnt/etc/kboot.conf 
FreeBSD_boot='/kernel/kernel vfs.root.mountfrom=zfs:zroot kernelname=/kernel/kernel'

**Comment by seanbruno** [comment]
> That link 404s :)
*sigh* ... why we have a "~" before our usernames nowadays ...

http://people.freebsd.org/~sbruno/pb-sos.tar.gz

**Comment by seanbruno** [comment]
> First thing to check would be that whatever configuration format you're using for FreeBSD sets a 'default' option though; Petitboot will use that to determine if a boot option is valid for autoboot.

Huh, I didn't see an example for default usage in the examples.  What's the syntax if you don't mind?

**Comment by sammj** [comment]
The format depends on the bootloader configuration file you're using, but for kboot a basic example is:
```
default=linux
linux='/vmlinux initrd=/initrd arg1=value1 arg2'
```
or in your case `default=FreeBSD_boot`

**Comment by seanbruno** [comment]
Yep, works flawlessly.  Thank you.
