### ISSUE TITLE
Solicit message spam

### ISSUE THREAD

**Issue by shenki** [open-power/petitboot#55]
A Palmetto system on our network started doing this on Jan 23rd:
 
> palm7-p1 is sending "Solicit message"s and then ignoring the DHCPv6 reply and sending the request again many times a second
> where "may times a second" equates to ~10000 in 30 seconds !

Versions:
 * petitboot-1.9.0
 * linux-4.18.3-openpower1-paea9c85
 * open-power-palmetto-c5daff7-dirty

**Comment by sammj** [comment]
Looks like that was it; that fix is in v1.9.1 and up for the record.
