### ISSUE TITLE
Booting a desktop system

### ISSUE THREAD

**Issue by skyne98** [open-power/petitboot#56]
Hey there! Using a full linux system as a bootloader to enable advanced features and improve boot times is a really fascinating idea, therefore I have a question: can petitboot be used for booting a linux-based operating system on a normal x86_64 desktop computer?

I understand I might be missing something very essential here, as the project seems to be aimed at the enterprise sector, but it is still interesting.

Thanks!

**Comment by stewart-ibm** [comment]
Aleksey Halahan <notifications@github.com> writes:
> Hey there! Using a full linux system as a bootloader to enable
> advanced features and improve boot times is a really fascinating idea,
> therefore I have a question: can petitboot be used for booting a
> linux-based operating system on a normal x86_64 desktop computer?

Petitboot just uses kexec, which is a kernel feature available on
x86_64, so yes! The bits where you may hit issues are if the drivers for
various devices don't behave themselves around kexec. We have seen bugs
along these lines on our OpenPOWER systems (which we then fix).
-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by sammj** [comment]
As Stewart says you absolutely can. For building a linux image most of the resources on open-power are obviously pretty power-specific, but you might find something useful in the Coreboot docs (eg. https://www.coreboot.org/Payloads)

**Comment by skyne98** [comment]
Thanks for your fast responses!

Right now I am trying to wrap my head around the relationships between all of those projects. As far as I have understood, coreboot can boot different payloads, one of which can happen to be petitboot.
I have one question though: does that mean that you will have boot sequence like coreboot -> petitboot -> linux (for booting) -> your linux distro? In that case, how does petitboot work around bootloader size limitations that are much smaller than required for storing a kernel? 

My guess will be that petitboot is a simple bootloader meant to boot a linux kernel somewhere in the memory after the bootloader. I hope that I am understanding this correctly! 😄

**Comment by stewart-ibm** [comment]
Aleksey Halahan <notifications@github.com> writes:
> Thanks for your fast responses!
>
> Right now I am trying to wrap my head around the relationships between all of those projects. As far as I have understood, coreboot can boot different payloads, one of which can happen to be petitboot.
> I have one question though: does that mean that you will have boot sequence like coreboot -> petitboot -> linux (for booting) -> your linux distro? In that case, how does petitboot work around bootloader size limitations that are much smaller than required for storing a kernel? 
>
> My guess will be that petitboot is a simple bootloader meant to boot a
> linux kernel somewhere in the memory after the bootloader. I hope that
> I am understanding this correctly! 😄

Petitboot is just a userspace program, so it'd be coreboot -> linux
(/bin/init launching petitboot) -> your linux distro.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by skyne98** [comment]
@stewart-ibm, yeah, did a little research and found out about that recently 👍 So now the challenge is to find a way to boot a linux instance from memory. I think I can try to have a look at coreboot.

Also, what about skiboot and skiroot? Are those particularly POWER specific?

**Comment by stewart-ibm** [comment]
Aleksey Halahan <notifications@github.com> writes:
> @stewart-ibm, yeah, did a little research and found out about that recently 👍 So now the challenge is to find a way to boot a linux instance from memory. I think I can try to have a look at coreboot.
>
> Also, what about skiboot and skiroot? Are those particularly POWER
> specific?

skiroot is the name we give to the kernel+initramfs environment where
petitboot lives.

skiboot is POWER specific and that's our runtime firmware.

-- 
Stewart Smith
OPAL Architect, IBM.
