### ISSUE TITLE
Shell prompt is displayed before kexec

### ISSUE THREAD

**Issue by artemsen** [open-power/petitboot#57]
When petitboot (ver. 1.10.1) initiates loading of a chosen system, it clears the terminal and prints title with shell prompt:
```
Exiting petitboot. Type 'exit' to return.
You may run 'pb-sos' to gather diagnostic data
No password set, running as root. You may set a password in the System Configuration screen.
# 
```
That prompt is not interactive and it looks like the system hangs for 3-5 seconds and then start kexec.
This behavior might be misleading to the end-user.

**Comment by sammj** [comment]
http://patchwork.ozlabs.org/patch/1047572/ addresses this issue, which I'll merge soon for a minor release.

**Comment by artemsen** [comment]
LGTM, thanks!

**Comment by sammj** [comment]
FYI this is now in v1.10.2
