### ISSUE TITLE
[witherspoon] petitboot does not retain boot order

### ISSUE THREAD

**Issue by manjo-git** [open-power/petitboot#58]
Witherspoon firmware version: witherspoon-IBM-OP9-v2.2-rc2-9.44_prod.pnor.squashfs.tar

After flashing this firmware, petitboot does not retain the boot order, it can retain the "network" device but nothing else. For example:

I added the following boot devices to the boot order.

```
Autoboot: ( ) Disabled
                 (*) Enabled

  Boot Order: (0) net: enP5p1s0f1 [mac: 08:94:ef:80:27:32]
                 (1) Any Disk device
                 (2) Any CD/DVD device

                 [ Add Device ]
                 [ Clear & Boot Any ]
                 [ Clear ]
```

I entered the petitboot shell and typed 'reboot'. After reboot, I checked the boot order I and see that other boot devices, *except net* were all removed from the boot order.
```
Autoboot: ( ) Disabled
                 (*) Enabled

  Boot Order: (0) net: enP5p1s0f1 [mac: 08:94:ef:80:27:32]

                 [ Add Device ]
                 [ Clear & Boot Any ]
                 [ Clear ]

```
It looks like a bug in petitboot since and it cannot keep boot devices like disk etc

**Comment by manjo-git** [comment]
This issue is also observed when I install the witherspoon, it is able to deploy the OS, but on 1st boot after install the boot order does not contain any *disk* devices, but it does retain the *net* device.

**Comment by sammj** [comment]
This logic hasn't been touched recently in Petitboot so I wonder if something is happening under the covers. Could you try
a) Setting the boot order, then dropping to the shell and running `pb-sos`.
b) Rebooting and running `pb-sos` again.

With these two sets of logs we can see what's happening before and after the change.

**Comment by manjo-git** [comment]
Please download the pb-sos files from [](http://people.canonical.com/~manjo/witherspoon/)
> This logic hasn't been touched recently in Petitboot so I wonder if something is happening under the covers. Could you try
> a) Setting the boot order, then dropping to the shell and running `pb-sos`.
file: pb-sos.before.tar.gz
> b) Rebooting and running `pb-sos` again.
> 
file: pb-sos.after.tar.gz

> With these two sets of logs we can see what's happening before and after the change.

**Comment by manjo-git** [comment]
oops..
pb-sos files located in:
http://people.canonical.com/~manjo/witherspoon/

**Comment by sammj** [comment]
Looks like you have an IPMI override set:
`[15:51:16]   IPMI boot device 0x01`
where 0x01 = network.
You should see a message in the configuration screen about this, is it there? There should also be an option to clear it.

Otherwise you can clear it remotely via `ipmitool -I lanplus -H host -U user -P pass chassis bootdev none`

**Comment by manjo-git** [comment]
Yes I see that the override was set, and I cleared it, set the boot order
to (0) Net and (1) Disk, and rebooted from petitboot shell. When I got back
in the petitboot menu after fw reboot, I still dont see the boot order I
had previously set. What I see is just the network device.

 Petitboot System Configuration
 ──────────────────────────────────────────────────────────────────────────────
  Autoboot:      ( ) Disabled

                 (*) Enabled

  Boot Order:    (0) net:  enP5p1s0f1 [mac: 08:94:ef:80:27:32]

                 [     Add Device     ]
                 [  Clear & Boot Any  ]
                 [       Clear        ]

  Timeout:       25    seconds


  Network:       (*) DHCP on all active interfaces
                 ( ) DHCP on a specific interface
                 ( ) Static IP configuration

I once again set the boot order, cleared any IPMI temporary settings, then
booted the system fully into the OS. Power cycled the system and I see
temporary IPMI boot option is set to network automatically on reboot, and
the boot order was cleared.
$ ipmitool -I lanplus -H 10.245.71.111 -P 0penBmc chassis power off
Chassis Power Control: Down/Off
$ ipmitool -I lanplus -H 10.245.71.111 -P 0penBmc chassis power on
Chassis Power Control: Up/On


Petitboot System Configuration
 ──────────────────────────────────────────────────────────────────────────────

  Autoboot:      ( ) Disabled

                 (*) Enabled

  Boot Order:    (0) net:  enP5p1s0f1 [mac: 08:94:ef:80:27:32]

                 [     Add Device     ]
                 [  Clear & Boot Any  ]
                 [       Clear        ]

  Timeout:       25    seconds

  Temporary IPMI boot option: Network
  Clear option:  [     Clear IPMI override now     ]

  Network:       (*) DHCP on all active interfaces
                 ( ) DHCP on a specific interface
                 ( ) Static IP configuration

**Comment by sammj** [comment]
Finally had a chance to test on a Witherspoon with the latest O9x0 update and Petitboot appears to be handling IPMI overrides as expect (ie. clearing temporary ones on boot).
Can you do the steps you mentioned about (set order, clear override) and grab a `pb-sos` before booting? This is starting to sound like more of an OpenBMC problem.

**Comment by manjo-git** [comment]
I can have that information posted here by Wednesday next week. Yes the
openbmc on this system is also an RC build I got from IBM.

**Comment by manjo-git** [comment]
Please find the pb-sos file here: http://people.canonical.com/~manjo/witherspoon/

**Comment by sammj** [comment]
A quick thought; when this happens if you select "Rescan" from the menu, do the missing devices appear?
If so this will be related to https://github.com/open-power/op-build/pull/2756, and issue with eudev. If not, I'll need to dig into this deeper.

**Comment by manjo-git** [comment]
I got petitboot firmware IBM-witherspoon-OP9-v2.2-9.56 from IBM, after installing this firmware I no longer have the problem of missing boot order.

**Comment by sammj** [comment]
Between those two builds we have these versions:
```
BM-witherspoon-OP9-v2.2-rc2-9.44
    op-build-v2.2-rc2-1-g951b4b0
    buildroot-2018.11.1-7-g5d7cc8c
    skiboot-v6.2.1
    hostboot-2fce6c0-p561d11b
    occ-12c8088
    linux-4.19.13-openpower1-p88886ff
    petitboot-1.10.1
    machine-xml-f7cffdb
    hostboot-binaries-hw021419a.930
    capp-ucode-p9-dd2-v4
    sbe-2e253ce
    hcode-hw022019a.930 
```
and
```
IBM-witherspoon-OP9-v2.2-9.56
    op-build-v2.2-14-g29f0ba6
    buildroot-2018.11.3-12-g222837a
    skiboot-v6.2-176-g261ca8e779e5
    hostboot-0b3f4e1-p64efa43
    occ-12c8088
    linux-4.19.26-openpower1-p278e5c6
    petitboot-v1.10.2
    machine-xml-e3e9aef
    hostboot-binaries-hw021419a.930
    capp-ucode-p9-dd2-v4
    sbe-1410677
    hcode-hw031219a.940 
```

Between v1.10.1 and v1.10.2 the only changes are related to boot messages and how versions are described, so nothing that would affect boot order. Perhaps instead something in Buildroot or Skiboot has been fixed. I'll have a look to see if we haven't missed something.
