### ISSUE TITLE
petiboot as a coreboot payload boot failure.

### ISSUE THREAD

**Issue by hanetzer** [open-power/petitboot#61]
So, I've taken upstream buildroot and added petitboot to it, built a kernel, initramfs,
and dtb for the samsung chromebook plus (rk3399-gru-kevin), packed them together
in a fit image and embedded them in coreboot as a payload. After some tinkering with
coreboot's own code I got it to run and get me to petitboot-nc, but attempting to load
and boot the gentoo linux on the emmc fails.

The pertinent log snippet is:
```
Booting 5.0.7-gentoo
Loaded linux kernel image from file:///var/petitboot/mnt/dev/mmcblk1p2/boot/vmlinuz-5.0.7-gentoo
Running boot hooks
Performing kexec load
Cannot read /tmp/tmp.XXXXXX
```
`/etc/kboot.conf`
`5.0.7-gentoo='/boot/vmlinuz-5.0.7-gentoo console=tty0 console=ttyS2,115200n8 earlyprintk=ttyS2,115200n8 init=/sbin/init root=PARTUUID=%U/PARTNROFF=1 rootwait rw noinitrd crashkernel=256M`

If you need more info please let me know.

**Comment by hanetzer** [comment]
oh, and this is petitboot-1.10.3, latest version of this writing.

**Comment by hanetzer** [comment]
Further update. I've changed from kboot.conf to the native petitboot.conf,
this seems to work, but it hangs (I can still ctrl+c out of it) at 'Performing kexec reboot'

**Comment by sammj** [comment]
Once it appears to hang, drop to the shell and run `pb-sos`. This collects up some logs to see where that's failing; possibly kexec is hitting an issue in the background with the payload.

**Comment by oohal** [comment]
You can also try dropping to the shell and invoking kexec manually.

**Comment by hanetzer** [comment]
@sammj @oohal actually got to a workingish point. passing a dtb is apparently borked atm
for arm64 kexec, so pass none and it will reuse the current one.

Current issue is as follows: https://bpaste.net/show/a4bae13675a2

**Comment by hanetzer** [comment]
@sammj @oohal actually got to a workingish point. passing a dtb is apparently borked atm
for arm64 kexec, so pass none and it will reuse the current one.

Current issue is as follows: https://bpaste.net/show/a4bae13675a2

**Comment by hanetzer** [comment]
Fixed. Was probably some missing kernel config bit.
