### ISSUE TITLE
How complex would be to implement f2fs file system

### ISSUE THREAD

**Issue by JanuszChmiel** [open-power/petitboot#63]
Dear specialists,
One programmers have told Me, that The best file system for SD cards and SUSB flash disks is f2fs.
But unfortunately, very very little installers for various Linux distributions officially support it. And unfortunately, default automatic partitioning schemes of The majority of installers do not create this file system. So I have The question.
Is it possible to install Petitboot as boot loader to The f2fs file system on SD cart?
If no, is it possible to install Petitboot to EFI partition and install it to boot Linux distribution which is stored on SD card? Sure which will use EXT4.
I have read somewhere, that newest GRUB boot loader should support f2fs file system.
So do you think, that it would be possible to add support for f2fs  to Petitboot?
By The way, yours boot loader is very probably The only one, which allow booting various Linux distributions with Brltty support on its boot screen. So even visually impaired user with no sight at all can boot various Linux distributions while reading boot item name on his Braille display.
Thank you very much for yours answer.
With biggest regards.
Janusz Chmiel

**Comment by sammj** [comment]
There's nothing stopping Pettiboot from reading from F2FS partitions; you would just have to make sure that the kernel Petitboot is built with enables it (ie. `CONFIG_F2FS_FS` etc).
> If no, is it possible to install Petitboot to EFI partition and install it to boot Linux distribution which is stored on SD card?

This should work fine. You _could_ install it to the sdcard as well but something else would need to boot it in the first place.

> By The way, yours boot loader is very probably The only one, which allow booting various Linux distributions with Brltty support on its boot screen

This is very interesting! I haven't come across Brltty before.
