### ISSUE TITLE
"h=help" function key doesn't work in Petitboot Language Selection page

### ISSUE THREAD

**Issue by deathscytheh28** [open-power/petitboot#7]
No help description when we press "h" in Petitboot Language Selection page

**Comment by sammj** [comment]
Hi,
We don't currently have a help screen in the language-select screen since there's not much to say beyond "Please select a language". Potentially I'd be more in favour of removing the "h=help" part of the help message :)

**Comment by deathscytheh28** [comment]
Will you remove the "h=help" part in the next commit?

Thanks.

**Comment by sammj** [comment]
Fixed by https://github.com/open-power/petitboot/commit/827f09ff5864d80eef911fb235bfc3c0cbc90037
