### ISSUE TITLE
"shift+tab=previours" function key works abnormal in Petitboot

### ISSUE THREAD

**Issue by deathscytheh28** [open-power/petitboot#8]
When we press "shift+tab" in Petitboot Language Selection page, it goes next not previous.

**Comment by sammj** [comment]
Can you describe exactly what you see? At the moment "tab" and "shift-tab" are used for skipping through major screen elements - for example "tab" will jump down to the OK button, then Cancel, then back to the top. "shift-tab" works the same way in reverse.

**Comment by deathscytheh28** [comment]
We found the behavior between console output and VGA output is different. On console output, "tab" and "shift-tab" works as you said, but on VGA output, "tab" and "shift+tab" works the same.

**Comment by sammj** [comment]
As a quick test, if you drop to the shell while on the VGA console and enter
`stty raw ; hexdump -C -n 10; stty sane`
then press shift-tab several times until the command returns, what output do you get?. For example, you will probably see something like this:
> ^[[Z^[[Z^[[Z^[[Z00000000  1b 5b 5a 1b 5b 5a 1b 5b  5a 1b ...

**Comment by deathscytheh28** [comment]
Here is my result:
![result](https://cloud.githubusercontent.com/assets/10702657/13447772/040cd350-e059-11e5-8ce1-6cfe724e2543.png)

**Comment by jk-ozlabs** [comment]
Looks like the TTY is sending tab characters (0x09) when you hit shift-tab there.

We may need to check we have the correct terminal type when we set it up for input modes...

**Comment by sammj** [comment]
This is fixed by commit https://github.com/open-power/op-build/commit/de7fcc6f553d34d0b7a1359f6f838fddf136c538 in op-build.
