### ISSUE TITLE
The link to http://git.ozlabs.org/?p=petitboot might be confusing

### ISSUE THREAD

**Issue by adelton** [open-power/petitboot#88]
I tried to figure out what is the current canonical upstream of petitboot.

The https://github.com/open-power/petitboot/blob/master/README.md says

> Petitboot's home is at ozlabs.org; clone it with git clone git://git.ozlabs.org/petitboot.

while also linking to http://git.ozlabs.org/?p=petitboot.

However, that repo also says

> last change	Fri, 21 Jun 2019 04:42:20 +0100 (13:42 +1000)

The repository on GitHub is where development seems to be going on since 2019.

If git://git.ozlabs.org/petitboot is no longer the home of active development of petitboot, could the README.md here be updated to reflect that?

**Comment by jk-ozlabs** [comment]
Good plan - will update this soon.

**Comment by adelton** [comment]
Thanks!

**Comment by constant-current** [comment]
It might as well be useful to want to update http://www.kernel.org/pub/linux/kernel/people/geoff/petitboot/petitboot.html
ping @glevand who seems to have lost track of this project ;)
